/**
 * AI Feedback Results Component
 * 
 * Displays AI-generated spending analysis, insights, and recommendations
 * in a visually appealing and actionable format
 */

import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import {
    Alert,
    ScrollView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import { AIFeedbackResponse } from '../../types/receipt';

interface AIFeedbackResultsProps {
  feedbackData: AIFeedbackResponse;
  monthLabel: string;
  onClose: () => void;
  onRequestNewAnalysis?: () => void;
}

const AIFeedbackResults: React.FC<AIFeedbackResultsProps> = ({
  feedbackData,
  monthLabel,
  onClose,
  onRequestNewAnalysis,
}) => {
  const handleShareFeedback = async () => {
    try {
      if (!feedbackData.success || !feedbackData.feedback) {
        Alert.alert('Error', 'No feedback data to share');
        return;
      }

      const { feedback } = feedbackData;
      const shareText = `
🤖 AI Spending Analysis for ${monthLabel}

📊 SUMMARY:
${feedback.summary}

💡 KEY INSIGHTS:
${feedback.insights.map((insight, index) => `${index + 1}. ${insight}`).join('\n')}

🎯 RECOMMENDATIONS:
${feedback.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

✅ ACTION ITEMS:
${feedback.actionItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}

Generated by The Ledger AI
      `.trim();

      await Share.share({
        message: shareText,
        title: `AI Spending Analysis - ${monthLabel}`,
      });
    } catch (error) {
      console.error('Error sharing feedback:', error);
      Alert.alert('Error', 'Could not share feedback');
    }
  };

  const handleRetryAnalysis = () => {
    Alert.alert(
      'Request New Analysis',
      'This will generate a fresh AI analysis for the same month. Continue?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Generate New', 
          onPress: onRequestNewAnalysis,
          style: 'default'
        }
      ]
    );
  };

  if (!feedbackData.success) {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Analysis Failed</Text>
          <TouchableOpacity onPress={onClose} style={styles.closeButton}>
            <Ionicons name="close" size={24} color="#007AFF" />
          </TouchableOpacity>
        </View>

        <View style={styles.errorContainer}>
          <Ionicons name="warning-outline" size={64} color="#FF3B30" />
          <Text style={styles.errorTitle}>Analysis Unavailable</Text>
          <Text style={styles.errorMessage}>
            {feedbackData.error || 'Could not generate AI feedback at this time. Please try again later.'}
          </Text>
          
          {onRequestNewAnalysis && (
            <TouchableOpacity 
              style={styles.retryButton} 
              onPress={onRequestNewAnalysis}
            >
              <Ionicons name="refresh" size={20} color="#FFFFFF" />
              <Text style={styles.retryButtonText}>Try Again</Text>
            </TouchableOpacity>
          )}
        </View>
      </View>
    );
  }

  const { feedback } = feedbackData;

  if (!feedback) {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>No Feedback Data</Text>
          <TouchableOpacity onPress={onClose} style={styles.closeButton}>
            <Ionicons name="close" size={24} color="#007AFF" />
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerContent}>
          <Text style={styles.title}>AI Analysis</Text>
          <Text style={styles.monthLabel}>{monthLabel}</Text>
        </View>
        <View style={styles.headerActions}>
          <TouchableOpacity onPress={handleShareFeedback} style={styles.actionButton}>
            <Ionicons name="share-outline" size={20} color="#007AFF" />
          </TouchableOpacity>
          {onRequestNewAnalysis && (
            <TouchableOpacity onPress={handleRetryAnalysis} style={styles.actionButton}>
              <Ionicons name="refresh-outline" size={20} color="#007AFF" />
            </TouchableOpacity>
          )}
          <TouchableOpacity onPress={onClose} style={styles.actionButton}>
            <Ionicons name="close" size={20} color="#007AFF" />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Summary Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="analytics-outline" size={20} color="#007AFF" />
            <Text style={styles.sectionTitle}>Summary</Text>
          </View>
          <Text style={styles.summaryText}>{feedback.summary}</Text>
        </View>

        {/* Insights Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="bulb-outline" size={20} color="#FF9500" />
            <Text style={styles.sectionTitle}>Key Insights</Text>
          </View>
          {feedback.insights.map((insight, index) => (
            <View key={index} style={styles.listItem}>
              <View style={styles.bulletPoint}>
                <Text style={styles.bulletText}>{index + 1}</Text>
              </View>
              <Text style={styles.listItemText}>{insight}</Text>
            </View>
          ))}
        </View>

        {/* Recommendations Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="star-outline" size={20} color="#34C759" />
            <Text style={styles.sectionTitle}>Recommendations</Text>
          </View>
          {feedback.recommendations.map((recommendation, index) => (
            <View key={index} style={styles.listItem}>
              <View style={[styles.bulletPoint, styles.recommendationBullet]}>
                <Ionicons name="checkmark" size={16} color="#FFFFFF" />
              </View>
              <Text style={styles.listItemText}>{recommendation}</Text>
            </View>
          ))}
        </View>

        {/* Action Items Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="list-outline" size={20} color="#FF3B30" />
            <Text style={styles.sectionTitle}>Action Items</Text>
          </View>
          {feedback.actionItems.map((action, index) => (
            <TouchableOpacity 
              key={index} 
              style={styles.actionItem}
              onPress={() => {
                // Could implement action item completion tracking here
                Alert.alert('Action Item', action, [
                  { text: 'Mark Complete', style: 'default' },
                  { text: 'Remind Later', style: 'cancel' }
                ]);
              }}
            >
              <View style={styles.actionBullet}>
                <Ionicons name="ellipse-outline" size={12} color="#FF3B30" />
              </View>
              <Text style={styles.actionItemText}>{action}</Text>
              <Ionicons name="chevron-forward" size={16} color="#C7C7CC" />
            </TouchableOpacity>
          ))}
        </View>

        {/* Budget Analysis Section (if available) */}
        {feedback.budgetAnalysis && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="wallet-outline" size={20} color="#5856D6" />
              <Text style={styles.sectionTitle}>Budget Analysis</Text>
            </View>
            
            <View style={styles.budgetMetric}>
              <Text style={styles.budgetLabel}>Budget Utilization</Text>
              <View style={styles.utilizationBar}>
                <View 
                  style={[
                    styles.utilizationFill,
                    { 
                      width: `${Math.min(100, feedback.budgetAnalysis.budgetUtilization)}%`,
                      backgroundColor: feedback.budgetAnalysis.budgetUtilization > 100 ? '#FF3B30' : '#34C759'
                    }
                  ]} 
                />
              </View>
              <Text style={styles.utilizationText}>
                {feedback.budgetAnalysis.budgetUtilization}%
              </Text>
            </View>

            {feedback.budgetAnalysis.overspentCategories.length > 0 && (
              <View style={styles.budgetAlert}>
                <Ionicons name="warning" size={16} color="#FF3B30" />
                <Text style={styles.budgetAlertText}>
                  Overspent: {feedback.budgetAnalysis.overspentCategories.join(', ')}
                </Text>
              </View>
            )}

            {feedback.budgetAnalysis.underspentCategories.length > 0 && (
              <View style={styles.budgetSuccess}>
                <Ionicons name="checkmark-circle" size={16} color="#34C759" />
                <Text style={styles.budgetSuccessText}>
                  Under budget: {feedback.budgetAnalysis.underspentCategories.join(', ')}
                </Text>
              </View>
            )}
          </View>
        )}

        {/* Trends Section (if available) */}
        {feedback.trends && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Ionicons name="trending-up-outline" size={20} color="#007AFF" />
              <Text style={styles.sectionTitle}>Trends</Text>
            </View>
            {feedback.trends.comparedToPrevious && (
              <Text style={styles.trendsText}>{feedback.trends.comparedToPrevious}</Text>
            )}
            {feedback.trends.seasonalNotes && (
              <Text style={styles.trendsText}>{feedback.trends.seasonalNotes}</Text>
            )}
          </View>
        )}

        {/* Processing Time Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Analysis completed in {feedbackData.processingTime ? '< 1s' : 'unknown time'}
          </Text>
          <Text style={styles.footerSubtext}>
            Powered by AI • The Ledger
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E7',
  },
  headerContent: {
    flex: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  monthLabel: {
    fontSize: 14,
    color: '#6D6D70',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: 8,
    marginLeft: 8,
  },
  closeButton: {
    padding: 4,
  },
  scrollView: {
    flex: 1,
  },
  section: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    marginLeft: 8,
  },
  summaryText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#1C1C1E',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  bulletPoint: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  recommendationBullet: {
    backgroundColor: '#34C759',
  },
  bulletText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  listItemText: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#1C1C1E',
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    marginBottom: 8,
  },
  actionBullet: {
    marginRight: 12,
  },
  actionItemText: {
    flex: 1,
    fontSize: 16,
    color: '#1C1C1E',
  },
  budgetMetric: {
    marginBottom: 16,
  },
  budgetLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  utilizationBar: {
    height: 8,
    backgroundColor: '#F2F2F7',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  utilizationFill: {
    height: '100%',
  },
  utilizationText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6D6D70',
    textAlign: 'right',
  },
  budgetAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2F2',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  budgetAlertText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#FF3B30',
    flex: 1,
  },
  budgetSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2FFF2',
    padding: 12,
    borderRadius: 8,
  },
  budgetSuccessText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#34C759',
    flex: 1,
  },
  trendsText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#1C1C1E',
    marginBottom: 8,
  },
  footer: {
    padding: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 14,
    color: '#6D6D70',
  },
  footerSubtext: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 4,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1C1C1E',
    marginTop: 16,
  },
  errorMessage: {
    fontSize: 16,
    color: '#6D6D70',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 24,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 20,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
});

export default AIFeedbackResults;